# Generated by Django 2.2.4 on 2019-12-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(help_text='Anything to help find the document'),
        ),
    ]
