# Generated by Django 2.2.4 on 2019-11-01 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20191101_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, related_name='answer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, related_name='question', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
