# Generated by Django 2.2.4 on 2019-11-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20191101_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
