# Generated by Django 2.2.4 on 2019-12-05 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_auto_20191205_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, related_name='answer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
